rstudio:

  ingress: 
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: rstudio.homelab.bartbrinkman.nl
      paths:
      - path: /
    tls:
    - secretName: rstudio-tls
      hosts:
      - rstudio.homelab.bartbrinkman.nl

  service:
    openshiftRoute:
      enabled: false
    openshift:
      tls:
        enabled: false 

  password: stupid
        