sealed-secrets-web:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: sealed-secrets-web.homelab.bartbrinkman.nl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: sealed-secrets-web-tls
        hosts:
          - sealed-secrets-web.homelab.bartbrinkman.nl