sealed-secrets-web:
  ingress:
    enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: sealed-secrets-web.homelab.bartbrinkman.nl
      tls:
        - secretName: sealed-secrets-web-tls
          hosts:
            - hsealed-secrets-web.homelab.bartbrinkman.nl