apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: rstudio
  namespace: rstudio
spec:
  ingressClassName: nginx
  rules:
    - host: rstudio.homelab.bartbrinkman.nl
      http:
        paths:
          - backend:
              service:
                name: rstudio
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - rstudio.homelab.bartbrinkman.nl
      secretName: rstudio-tls


